common:
  namespace: mysql


mysql:
  image:
    name: mysql
    repository: mysql
    version: 8.0

  secrets:
    MYSQL_ROOT_PASSWORD: "1234" # Base64 encoding for "1234"
    MYSQL_USER: app_user # Base64 encoding for "app_user"
    MYSQL_PASSWORD: "1234" # Base64 encoding for "1234"

  spec:
    replicas: 2

  volumeClaimTemplates:
    spec:
      resources:
        requests:
          storage: 2Gi

  toleration:
    - key: "app"
      operator: "Equal"
      value: "mysql"
      effect: "NoSchedule"

  affinity:
    - key: "app"
      operator: In
      values:
      - mysql

  resources:
    requests:
      cpu: 500m
      memory: 1Gi