apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.common.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  replicas: {{.Values.mysql.spec.replicas}}
  serviceName: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Values.mysql.image.name}}
        image: {{.Values.mysql.image.repository}}:{{.Values.mysql.image.version}}
        env:
        {{- range $k, $v := .Values.mysql.secrets}}
        - name: {{$k}}
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: {{$k}}
        {{- end}}
        - name: MYSQL_DATABASE
          value: app_db
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: {{.Values.mysql.resources.requests.cpu}}
            memory: {{.Values.mysql.resources.requests.memory}}
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: config-map
        configMap:
          name: {{.Chart.Name}}
      tolerations:
      {{- range .Values.mysql.toleration}}
      - key: {{.key}}
        operator: {{.operator}}
        value: {{.value}}
        effect: {{.effect}}
      {{- end}}
      affinity:
      {{- range .Values.mysql.affinity}}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: {{.key}}
                    operator: In
                    values:
                    {{- range .values}}
                      - {{.}}
                    {{- end}}
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{.key}}
                    operator: In
                    values:
                    {{- range .values}}
                      - {{.}}
                    {{- end}}
      {{- end}}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{.Values.mysql.volumeClaimTemplates.spec.resources.requests.storage}}