apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.common.namespace}}
spec:
  strategy:
    type: {{.Values.todoapp.strategy.type}}
    rollingUpdate:
      maxSurge: {{.Values.todoapp.strategy.rollingUpdate.maxSurge}}
      maxUnavailable: {{.Values.todoapp.strategy.rollingUpdate.maxUnavailable}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      serviceAccountName: secrets-reader
      containers:
      - name: {{.Values.todoapp.image.name}}
        image: {{.Values.todoapp.image.repository}}:{{.Values.todoapp.image.version}}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: {{.Chart.Name}}-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: {{.Chart.Name}}-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.todoapp.resources.requests.memory}}
            cpu: {{ .Values.todoapp.resources.requests.cpu}}
          limits:
            memory: {{ .Values.todoapp.resources.limits.memory}}
            cpu: {{ .Values.todoapp.resources.limits.cpu}}
        env:
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: {{.Chart.Name}}-config
              key: PYTHONUNBUFFERED
        {{- range $k, $v := .Values.todoapp.secrets}}
        - name: {{$k}}
          valueFrom:
            secretKeyRef:
              name: todoapp-secret
              key: {{ $k}}
        {{- end}}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-data
      - name: {{.Chart.Name}}-secrets-volume
        secret:
          secretName: {{.Chart.Name}}-secret
      - name: {{.Chart.Name}}-config-volume
        configMap:
          name: {{.Chart.Name}}-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.todoapp.affinity}}
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .key }}
                operator: In
                values:
                {{- range .values }}
                  - {{.}}
                {{- end}}
          {{- end}}